header.css
vidklyk/project_team1 pull request #11
Opened 2024-10-18 23:47 UTC by Viktoriia-Tymets

Не до конца уверенна,что всё правильно,заранее спасибо)

2024-10-19 07:27 UTC, vidklyk requested changes
Потрібно виправляти код

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +padding-top:20px;
Потрібно поставити пробіл перед 20 px

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +.page-header{
Потрібно додати до хеддера абсолютне позиціювання та з ідекс, щоб хеддер завжди був поверх всіх елементів
  position: absolute;
  z-index: 999;

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +background:transparent;
Пробіл потрібно поставити перед transparent

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +    display:none;
Пробіл також

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> + .page-header{
пробіл перед дужками

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> + .header-container{
пробіл перед дужками

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +.header-nav{
пробіл перед дужками

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +@media screen and (min-width:1280px){
пробіл перед 1280px та кривими дужками

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +.menu-nav{
пробіл перед дужками

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +.header-button{
пробіл перед дужками

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +padding-top:16px;
пробіл перед 16px

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +.header-button:hover{
пробіл перед дужками

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +.burger-btn{
пробіл перед дужками

2024-10-19 07:27 UTC, vidklyk commented on src/css/header.css
> +position: fixed;
Треба прибрати

2024-10-19 09:52 UTC, Viktoriia-Tymets commented on src/css/header.css
> +padding-top:20px;
Всё исправила

2024-10-19 10:43 UTC, vidklyk requested changes

2024-10-19 10:43 UTC, vidklyk commented on src/css/header.css
> + .header-container{
Не виправили пробіл перед дужками

2024-10-19 11:16 UTC, vidklyk requested changes
Зверніть увагу

2024-10-19 11:16 UTC, vidklyk commented on src/css/header.css
> +.page-header{
Так й залишився пробіл перед дужками

2024-10-19 20:59 UTC, Viktoriia-Tymets commented on src/css/header.css
> +.page-header{
вроде всё исправила

2024-10-20 09:34 UTC, vidklyk approved these changes
Зробив зміни в коді, та прийняв йього.
Додав ще у 
.page-header {
  left: 50%;
  transform: translateX(-50%);
  top: 0;
  width: 100%;
  top: 0;

2024-10-20 09:34 UTC, vidklyk commented on src/css/header.css
> +.page-header {
Додав сюди ще цей код:
  left: 50%;
  transform: translateX(-50%);
  top: 0;
  width: 100%;

2024-10-20 09:34 UTC, merged