advertisement.css
vidklyk/project_team1 pull request #20
Opened 2024-10-19 13:01 UTC by ankhod

2024-10-19 13:32 UTC, vidklyk requested changes
Багато помилок, потрібно виправляти.

2024-10-19 13:32 UTC, vidklyk commented on src/css/advertisement.css
> +.container {
Видалити контейнер, та не працювати з ним, йьому вже задані глобальні правила

2024-10-19 13:32 UTC, vidklyk commented on src/css/advertisement.css
> +  font: 600 48px / 1.04 'Inter Tight', sans-serif;
Видалити це, шрифт вже заданий у боді

2024-10-19 13:32 UTC, vidklyk commented on src/css/advertisement.css
> +  gap: 10px;
До чого тут гепи, в нас немає елементів, окрім тексту, видалити геп

2024-10-19 13:32 UTC, vidklyk commented on src/css/advertisement.css
> +.advertisement-discount {
задати padding: 3px 10px 0 10px;

2024-10-19 13:32 UTC, vidklyk commented on src/css/advertisement.css
> +.container {
Потрібно додати advertisement та додати туди background-color: #FBFBFB;

2024-10-19 14:15 UTC, ankhod commented on src/css/advertisement.css
> +  font: 600 48px / 1.04 'Inter Tight', sans-serif;
Якщо видаляю font все ламається

2024-10-19 14:27 UTC, vidklyk commented on src/css/advertisement.css
> +  font: 600 48px / 1.04 'Inter Tight', sans-serif;
Вставте це замість цього
font-size: 48px;
font-style: normal;
font-weight: 600;
line-height: 50px; /* 104.167% */
letter-spacing: -0.72px;

2024-10-19 15:30 UTC, vidklyk requested changes

2024-10-19 15:30 UTC, vidklyk commented on src/css/advertisement.css
>    letter-spacing: -0.01em;
тут два letter-spacing

2024-10-20 14:37 UTC, vidklyk approved these changes

2024-10-20 14:53 UTC, merged