css hero
vidklyk/project_team1 pull request #26
Opened 2024-10-20 17:25 UTC by Yuliya1981-art

2024-10-20 18:08 UTC, vidklyk requested changes
Потрібно виправити код

2024-10-20 18:08 UTC, vidklyk commented on src/css/hero.css
> +@media (min-width: 1024px) {
@media only screen and (min-width: 1280px)

2024-10-20 18:08 UTC, vidklyk commented on src/css/hero.css
> +@media (min-width: 768px) {
@media only screen and (min-width: 768px)

2024-10-20 18:08 UTC, vidklyk commented on src/css/hero.css
> +/* ----------- Мобільна версія (за замовчуванням) ----------- */
Потрібно додати в css background-image та додати фонове зображення та видалити зображення у HTML

2024-10-20 18:08 UTC, vidklyk commented on src/css/hero.css
> +@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
![зображення_2024-10-21_050508940](https://github.com/user-attachments/assets/4aa9f426-00f0-4c33-b818-f8c018d2d272)

2024-10-20 18:08 UTC, vidklyk commented on src/css/hero.css
> +
![зображення_2024-10-21_050805259](https://github.com/user-attachments/assets/9958bb0b-119b-49c3-a2c9-1b2b65eb6232)

2024-10-20 18:59 UTC, Yuliya1981-art commented on src/css/hero.css
> +/* ----------- Мобільна версія (за замовчуванням) ----------- */
Не зрозумила. В HTML ніяких зображень я не додавала, в мене виключно зображення в css і вони добавлені як фонові

2024-10-20 19:01 UTC, Yuliya1981-art commented on src/css/hero.css
> +@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
а тут знайшла, клас не вірно зазначений в ретине

2024-10-20 21:32 UTC, Yuliya1981-art commented on src/css/hero.css
> +
я не понимаю, как это исправить.

2024-10-20 21:37 UTC, Yuliya1981-art commented on src/css/hero.css
> +
дело в том, что я не могу запустить живую страницу нашего проекта. окно с живой страницей выглядит 
![image](https://github.com/user-attachments/assets/ce646f8d-c9ad-4b4c-9ba2-8bcefb67ca3b), и как открыть сайт  я не понимаю. Весь код я делала в отдельно созданном проекте, где нормально открывается живая страница. И я  не понимаю, что меняет мне размер секции.

2024-10-20 21:44 UTC, Yuliya1981-art commented on src/css/hero.css
> +
я пофиксила, что смогла, здесь я не понимаю, что делать.

2024-10-20 21:49 UTC, Yuliya1981-art commented on src/css/hero.css
> +
и я вижу, что и с отступом от параграфа не все гуд, но опять же я не могу открыть сайт и инструмент разработчика  в нашем проекте, чтоб посмотреть, что там с маржинами, а в отдельном файле, в котором я работала, было все нормально

2024-10-21 16:14 UTC, vidklyk approved these changes
Виправив код

2024-10-21 16:15 UTC, merged